# This is the name of the workflow, visible on GitHub UI.
name: TestCompile
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  build:
    name: Test compiling aurora for ESP32
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout ESPAsyncWebServer library
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/ESPAsyncWebServer
          ref: master
          path: CustomLibrary_ESPAsyncWebServer

      - name: Checkout AsyncTCP library
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/AsyncTCP
          ref: master
          path: CustomLibrary_AsyncTCP

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@v2.5.0
        with:
          sketch-names: aurora.ino
          sketch-names-find-start: SOURCES/WEBAPP/ESP32/aurora/
          arduino-board-fqbn: esp32:esp32:esp32
          platform-url: https://dl.espressif.com/dl/package_esp32_index.json
          required-libraries: ArduinoJson

